- public/index.html
- src/Page/Programmer/index.js
Removed all commented code and reviewed it.
Added Apple-touch-icon.
> Apple icon

- src/Global.css
- src/Page/CIFpage/index.js
- src/Page/Donate/index.js
- src/Page/HomePage/index.js
- src/Page/NGLabs/index.js
- src/Page/NgHiring/index.js
- src/Page/Partners/index.js
- src/Page/Privacy/index.js
- src/Page/Programmer/index.js
1. Spacing Changed on some pages
2. Filter Applied on Alumni page
3. Website icon's order re-arranged on the partners page.
> Spacing changes

- src/Page/Donate/index.js
> Donate page updated

- src/Page/CampusPages/index.js
- src/Page/CampusPages/style.css
Added campuses name and it's info
> Added campuses name

- src/Page/TeamPage/index.js
Updated the URL for the (Careers at Navgurukul)
> Fixing the team page bugs

- package-lock.json
- src/Global.css
- src/Page/Donate/index.js
- src/Page/Donate/styles.css
- yarn.lock
> new donate page

- src/Page/Donate/index.js
- src/Page/Donate/styles.css
> Fixed the bugs

- src/Page/Donate/IndianDonate.js
- src/Page/Donate/index.js
> indian donate page

- src/Page/Header/index.js
- src/Page/Header/styles.css
- src/Page/HomePage/DigitalInitiatives/style.css
- src/Page/HomePage/KeyFacilities/style.css
- src/Page/HomePage/SupporterSlider/index.js
- src/Page/HomePage/index.js
- src/Page/HomePage/style.css
> Bug fixing

- src/Page/SchoolsPages/BCAProgram/index.js
- src/Page/SchoolsPages/BCAProgram/style.css
- src/Page/SchoolsPages/ProgramDetails/CourseDetail.js
- src/Page/SchoolsPages/ProgramDetails/style.css
- src/Page/SchoolsPages/SchoolOfBusiness/Data.js
- src/Page/SchoolsPages/SchoolsOfDesign/index.js
- src/Page/SchoolsPages/ScreningTest/index.js
- src/Page/SchoolsPages/ScreningTest/style.css
School page and BCA page changes
> school page changes

- src/Page/Header/index.js
- src/Page/Header/styles.css
> fixed button

- src/Page/Donate/index.js
- src/Page/Donate/styles.css
> donate buttons

- src/Page/Header/index.js
- src/Page/SchoolsPages/Programing/index.js
- src/Page/SchoolsPages/SchoolOfBusiness/index.js
- src/Page/SchoolsPages/SchoolOfFinance/index.js
- src/Page/SchoolsPages/SchoolsOfDesign/index.js
- src/Page/SchoolsPages/ScreningTest/index.js
- src/Route/index.js
update design page and in route change the schools path
>  update design page and in route change the schools path

- src/Page/AboutPage/index.js
- src/Page/CampusPages/index.js
- src/Page/Donate/styles.css
- src/Page/OurCampus/index.js
- src/Page/Partners/index.js
- src/Page/SchoolsPages/BCAProgram/index.js
- src/Page/TeamPage/index.js
- src/Page/TeamPage/styles.css
> updated pages changes

- src/Page/AboutPage/index.js
- src/Page/Footer/index.js
- src/Page/Header/index.js
- src/Page/HomePage/DigitalInitiatives/index.js
> removed samyarth text

- src/Page/SchoolsPages/BCAProgram/index.js
changed the text from BCA page para
> changed the text from BCA page para

- src/Page/TeamPage/index.js
points:
1) added space between buttons .
2) added space between cards.
> update new page

- src/Page/HomePage/DigitalInitiatives/index.js
- src/Page/HomePage/OurCampuses/index.js
- src/Page/HomePage/style.css
1. Digital Initiatives section In the mobile view, external links and text given them more space .
2. Our Campuses images are visiable.
3. Fixed the sections part of 4 grid.
4.
> Homepage bugs

- src/Page/HomePage/OurCampuses/index.js
> images are showing on the local but not on the dev

- src/Page/TeamPage/index.js
- src/Page/TeamPage/styles.css
points:-
1) did correct team information card 
2) set button width
> Update new team page

- src/Page/Donate/index.js
- src/Page/HomePage/OurCampuses/index.js
Given button spacing and homepage campuses img
> Donate page

- src/Global.css
- src/Page/AboutPage/index.js
- src/Page/AboutPage/styles.css
- src/Page/Careers/index.js
- src/Page/Header/index.js
- src/Page/HomePage/AlumniStories/index.js
- src/Page/HomePage/AlumniStories/style.css
- src/Page/HomePage/DigitalInitiatives/index.js
- src/Page/HomePage/KeyFacilities/index.js
- src/Page/HomePage/OurCampuses/index.js
- src/Page/HomePage/OurCampuses/style.css
- src/Page/HomePage/index.js
- src/Page/HomePage/style.css
- src/Page/NgHiring/index.js
- src/Page/Partners/index.js
- src/Page/Partners/style.css
- src/Page/TeamPage/index.js
- src/Page/TeamPage/styles.css
Refactoring code of Ng website
> Refactoring code

- src/Global.css
- src/Page/SchoolsPages/AdmissionProcess/index.js
- src/Page/SchoolsPages/AlumnusPage/index.js
- src/Page/SchoolsPages/BgroundImg/index.js
- src/Page/SchoolsPages/BgroundImg/style.css
- src/Page/SchoolsPages/Programing/data.js
- src/Page/SchoolsPages/ScreningTest/index.js
I fixed the card on the admission page . i remove the col-lg-3 , just I use col.
> fix the card in admission page

- src/Page/HomePage/index.js
Removed the banner section from the home page.
> removed the banner

- src/Page/Header/index.js
- src/Page/Header/styles.css
Fixed the aligment of the responsive header text
> fixed the header responsive text alignment

- src/Page/NgHiring/index.js
> Removed the top spacing of the image section

- src/Page/NgHiring/index.js
Created new sheet and added it's functionality into it .
> Added new apis script

- src/Page/NgHiring/Data.js
- src/Page/NgHiring/Ourrecruiters/index.js
- src/Page/NgHiring/index.js
> Hiring buttons

- src/Page/NgHiring/index.js
> added slider part

- src/Page/HomePage/OurCampuses/index.js
> remove campus

- src/Page/TeamPage/Teamsecssion.js
- src/Page/TeamPage/index.js
resolved bug witch is coming on the teampage
> resolved bug witch is coming on the teampage
